config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :gaco_cms, path: GacoCms::Config.url_path do
    namespace :admin do
      get '/', to: 'base#index'
      post 'upload_file', controller: 'base'
      resources :page_types do
        resources :pages
      end
      resources :field_groups_manager, only: %i[index update] do
        get :group_tpl, on: :collection
        get :field_tpl, on: :collection
      end
      resources :field_groups_renderer, only: :index do
        get :render_group, on: :collection
        get :render_field, on: :collection
      end
      resources :themes
    end

    # frontend
    get '/', to: 'front#index'
    get 'page/:page_id', as: 'page', to: 'front#page'
    get ':page_title-:page_id', as: 'titled_page', to: 'front#page'
    get ':type_title/:page_title-:page_id', as: 'type_titled_page', to: 'front#page'
  end
end

app/models/concerns/gaco_cms/fields_assignable.rb
# frozen_string_literal: true

module GacoCms
  module FieldsAssignable
    extend ActiveSupport::Concern
    included do
      has_many :field_groups, -> { ordered }, as: :record, inverse_of: :record, dependent: :destroy
      has_many :fields, through: :field_groups
      has_many :field_values, dependent: :destroy, as: :record, inverse_of: :record
      accepts_nested_attributes_for :field_values, allow_destroy: true
      accepts_nested_attributes_for :field_groups, allow_destroy: true
    end

    def the_value(key, cache: true)
      callback = proc { field_values.ordered.find_by(field_key: key)&.the_value }
      return callback.call unless cache

      Rails.cache.fetch(cache_key_locale(:the_value, key), expires_at: Time.current.end_of_day, &callback)
    end

    def default_group
      @default_group ||= field_groups.where(key: :default).first_or_create(title: 'Basic Fields', key: :default)
    end

    def the_values(key, cache: true)
      callback = proc { field_values.ordered.where(field_key: key).map(&:the_value) }
      return callback.call unless cache

      Rails.cache.fetch(cache_key_locale(:the_values, key), expires_at: Time.current.end_of_day, &callback)
    end
    def the_group_values(key, cache: true)
      group = field_groups.find_by(key: key)
      return [] unless group

      multiple = group.fields.where(repeat: true).pluck(:key)
      the_grouped_values(*group.fields.pluck(:key), multiple: multiple, cache: cache)
    end

    # TODO: refactor complexity
    # the_grouped_values :name, :title, multiple: %w[slide_photos]
    def the_grouped_values(*keys, cache: true, multiple: [])
      callback = proc do
        values = field_values.where(field_key: keys + multiple)
        values.pluck(:group_no).uniq.sort.map do |g_no|
          res = {}
          values.where(group_no: g_no).each do |value|
            if multiple.include?(value.field_key.to_sym)
              res[value.field_key] ||= []
              res[value.field_key] << value.the_value
            else
              res[value.field_key] = value.the_value
            end
          end
          res
        end
      end
      return callback.call unless cache

      cache_key = cache_key_locale(:the_grouped_values2, keys.join('-'))
      Rails.cache.fetch(cache_key, expires_at: Time.current.end_of_day, &callback)
    end
  end
end

app/models/concerns/gaco_cms/union_scope.rb
# frozen_string_literal: true

module GacoCms
  module UnionScope
    extend ActiveSupport::Concern
    included do
      def self.union_scope(*scopes)
        id_column = "#{table_name}.id"
        sub_query = scopes.map { |s| s.reorder(nil).select(id_column).to_sql }.compact.join(' UNION ')
        where("#{id_column} IN (#{sub_query})")
      end
    end
  end
end

app/controllers/concerns/gaco_cms/turbo_concern.rb
module GacoCms
  module TurboConcern
    extend ActiveSupport::Concern
    included do
      layout -> { false if turbo_frame_request? || request.headers['No-Layout'] }
      around_action :parse_turbo_frame
    end

    private

    def parse_turbo_frame
      yield
      is_redirect = response.status == 302
      includes_layout = response.body.include?('<html>')
      return if is_redirect || includes_layout || %w[*/* html].none? { request.format.to_s.include?(_1) }

      render_turbo_content(response.body)
    end

    def render_turbo_content(content, turbo_target = turbo_frame_request_id) # rubocop:disable Metrics/AbcSize
      turbo_action = request.headers['Turbo-Response-Action'] || 'update'
      raise 'Invalid turbo action' if %w[update replace append append_all].exclude?(turbo_action)

      parse_turbo = turbo_target && response.status == 200 && !params[:turbo_response_skip]
      content = '' if params[:turbo_response_skip] # TODO: use headers instead
      content = "#{content}#{turbo_flash_response}"
      content = turbo_stream.send(turbo_action, turbo_target, content) if parse_turbo && !@skip_turbo_response_wrapper
      response.content_type = 'text/vnd.turbo-stream.html'
      response.body = content
    end

    # @return [String]
    def turbo_flash_response
      content = ''
      return content if @skip_turbo_response_flash

      flash_messages = render_to_string(partial: '/layouts/gaco_cms/flash_messages')
      # append: allows to persist flash messages
      content += turbo_stream.send(request.get? ? :append : :update, 'toasts', flash_messages)
      flash.clear # clear streamed flash messages
      content
    end

    def render_failure(model, run_turbo: false)
      error = model.is_a?(String) ? model : model.errors.full_messages.join('<br>')
      return render json: { error: }, status: :unprocessable_entity if request.format == 'json'

      if request.headers['X-Turbo-Request-Id'].present?
        flash[:error] = error
        render inline: '', status: :unprocessable_entity
        render_turbo_content(response.body) if run_turbo
      else
        @msg = error
        render '/dashboard/error'
      end
    end

    def turbo_request?
      request.headers['Turbo-Request'].present?
    end
  end
end

app/controllers/gaco_cms/admin/base_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class BaseController < GacoCms::AdminController
      skip_before_action :verify_authenticity_token, only: :upload_file

      def upload_file
        file = GacoCms::MediaFile.new(file: params[:file])
        if file.save
          render json: { location: file.url }
        else
          render json: { error: file.errors.full_message.join(', ') }
        end
      end

      def index; end
    end
  end
end

app/controllers/gaco_cms/admin/field_groups_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class FieldGroupsController < BaseController
      before_action :set_group, except: %i[index new create new_field]
      before_action { add_breadcrumb(FieldGroup.human_name(count: 2), url_for(action: :index)) }

      def index
        @groups = FieldGroup.ordered.all
      end

      def new
        @group = FieldGroup.new
        render :form
      end

      def create
        group = FieldGroup.new(group_params)
        if group.save
          redirect_to url_for(action: :index), notice: 'Group saved'
        else
          render inline: group.errors.full_messages.join(', ')
        end
      end

      def edit
        render :form
      end

      def update
        if @group.update(group_params)
          redirect_to url_for(action: :index), notice: 'Group updated'
        else
          render inline: @group.errors.full_messages.join(', ')
        end
      end

      def destroy
        @group.destroy!
        redirect_to url_for(action: :index), notice: 'Group destroyed'
      end

      def tpl
        locals = { group: @group, field_values: FieldValue.none, group_no: Time.current.to_i }
        render partial: '/gaco_cms/admin/fields/render/group', locals: locals
      end

      def new_field
        field = Field.new(kind: params[:kind])
        render partial: 'field', locals: { field: field }
      end

      private

      def group_params
        fix_record_param
        fix_fields_params
        params.require(:gaco_cms_field_group)
              .permit(:key, :record_id, :record_type, :repeat, :position,
                      title: permitted_locales, description: permitted_locales,
                      fields_attributes: [:id, :kind, :key, :repeat, :required,
                                          :translatable, :position, :_destroy,
                                          { title: permitted_locales, def_value: permitted_locales,
                                            description: permitted_locales }])
      end

      def set_group
        @group = FieldGroup.find(params[:id])
      end

      def fix_record_param
        record = params[:gaco_cms_field_group].delete(:record).to_s
        params[:gaco_cms_field_group][:record_type], params[:gaco_cms_field_group][:record_id] = record.split('/')
      end

      def fix_fields_params
        items = (params[:fields_attributes] || {}).values
        items.each do |item|
          def_val = item[:def_value]
          item[:def_value] = { en: def_val } if def_val && !def_val.is_a?(Hash)
        end
        params[:gaco_cms_field_group][:fields_attributes] = items
      end
    end
  end
end

app/controllers/gaco_cms/admin/field_groups_manager_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class FieldGroupsManagerController < BaseController
      before_action :set_record, only: %i[index update]

      # @option record_type [String]
      # @option record_id [Integer]
      # @option reload_frame [String]
      def index
        @groups = @record.field_groups
      end

      def group_tpl
        @group = FieldGroup.new
        render partial: 'group', locals: { group: @group }
      end

      # @option kind [String]
      def field_tpl
        field = Field.new(kind: params[:kind])
        render partial: 'field', locals: { field: field, parent_name: params[:parent_name] }
      end

      def update
        if @record.update(groups_params)
          render inline: ''
        else
          render inline: @record.errors.full_messages.join(', ')
        end
      end

      private

      # TODO: whitelist record_types
      def set_record
        @record = params[:record_type].constantize.find(params[:record_id])
      end

      def groups_params
        fix_groups_fields
        fix_fields_params
        fields_attrs = [:id, :kind, :key, :repeat, :required, :translatable, :position, :_destroy,
                        :title, :description, :template, { def_value: permitted_locales }]
        params.require(:groups_manager)
              .permit(field_groups_attributes: [:id, :key, :record_id, :record_type, :repeat, :position, :_destroy, :template,
                                                :title, :description, fields_attributes: fields_attrs])
      end

      def fix_groups_fields
        params[:groups_manager][:field_groups_attributes] = params[:groups_manager][:field_groups_attributes].values
      end

      def fix_fields_params
        params[:groups_manager][:field_groups_attributes].each do |group_attrs|
          group_attrs[:fields_attributes] = (group_attrs[:fields_attributes] || {}).values
          group_attrs[:fields_attributes].each do |field_attr|
            def_val = field_attr[:def_value]
            field_attr[:def_value] = { en: def_val } if def_val && !def_val.is_a?(Hash)
          end
        end
      end
    end
  end
end

app/controllers/gaco_cms/admin/field_groups_renderer_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class FieldGroupsRendererController < BaseController
      before_action :set_record, only: %i[index]

      def index
        @groups = @record.field_groups
        @groups = @record.page_type.field_groups if params[:parent] && @record.is_a?(Page)
      end

      def render_group
        group = FieldGroup.find(params[:group_id])
        locals = { group: group, field_values: FieldValue.none, group_no: Time.current.to_i }
        render partial: 'group', locals: locals
      end

      def render_field
        field = Field.find(params[:field_id])
        value = field.field_values.new(group_no: params[:group_no])
        render partial: 'field', locals: { value: value }
      end

      private

      # TODO: whitelist record_types
      def set_record
        @record = params[:record_type].constantize.find(params[:record_id])
      end
    end
  end
end

app/controllers/gaco_cms/admin/fields_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class FieldsController < BaseController
      before_action :set_field

      def tpl
        value = @field.field_values.new(group_no: params[:group_no])
        render partial: '/gaco_cms/admin/fields/render/field', locals: { value: value }
      end

      private

      def set_field
        @field = Field.find(params[:id])
      end
    end
  end
end

app/controllers/gaco_cms/admin/page_types_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class PageTypesController < BaseController
      before_action :set_page_type, only: %i[edit update destroy]
      before_action { add_breadcrumb(PageType.human_name(count: 2), url_for(action: :index)) }

      def index
        @page_types = PageType.all.title_ordered
      end

      def new
        @page_type = PageType.new
        render :form
      end

      def create
        page_type = PageType.new(page_type_params)
        if page_type.save
          redirect_to url_for(action: :index), notice: 'PageType saved'
        else
          render inline: page_type.errors.full_message.join(', ')
        end
      end

      def edit
        render :form
      end

      def update
        if @page_type.update(page_type_params)
          redirect_to url_for(action: :index), notice: 'PageType saved'
        else
          render inline: @page_type.errors.full_message.join(', ')
        end
      end

      def destroy
        @page_type.destroy!
        redirect_to url_for(action: :index), notice: 'PageType destroyed'
      end

      private

      def page_type_params
        params.require(:gaco_cms_page_type)
              .permit(:key, :template, title: permitted_locales)
      end

      def set_page_type
        @page_type = PageType.find(params[:id])
      end
    end
  end
end

app/controllers/gaco_cms/admin/pages_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class PagesController < BaseController
      before_action :set_page_type
      before_action :set_page, only: %i[edit update destroy]
      before_action :set_breadcrumb

      def index
        @pages = @page_type.pages.order(updated_at: :desc)
      end

      def new
        @page = @page_type.pages.new
      end

      def create
        page = @page_type.pages.new(page_params)
        if page.save
          redirect_to url_for(action: :edit, id: page), notice: 'Page created'
        else
          render inline: page.errors.full_messages.join(', ')
        end
      end

      def edit; end

      def update
        if @page.update(page_params)
          flash[:notice] = 'Page saved'
          render inline: ''
        else
          render inline: @page.errors.full_messages.join(', ')
        end
      end

      def destroy
        @page.destroy!
        redirect_to url_for(action: :index), notice: 'Page destroyed'
      end

      private

      def page_params
        fix_fields_values_param(:gaco_cms_page)
        params.require(:gaco_cms_page)
              .permit(:key, :template, :photo_url,
                      content: permitted_locales, summary: permitted_locales, title: permitted_locales,
                      field_values_attributes: permitted_field_values_params)
      end

      def set_page
        @page = @page_type.pages.find(params[:id])
      end

      def set_page_type
        @page_type = PageType.find_by(key: params[:page_type_id]) || PageType.find(params[:page_type_id])
      end

      def set_breadcrumb
        type_id = @page_type ? @page_type.id : @page.page_type_id
        name = @page_type ? @page_type.title : @page.page_type.title
        add_breadcrumb(name, edit_gaco_cms_admin_page_type_path(type_id))

        url = gaco_cms_admin_page_type_pages_path(page_type_id: @page_type ? @page_type.id : @page.page_type_id)
        add_breadcrumb(Page.human_name(count: 2), url)
      end
    end
  end
end

app/controllers/gaco_cms/admin/themes_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class ThemesController < BaseController
      before_action :set_theme, except: %i[index new create]
      before_action { add_breadcrumb(Theme.human_name(count: 2), url_for(action: :index)) }

      def index
        @themes = Theme.ordered.all
      end

      def new
        @theme = Theme.new
      end

      def create
        theme = Theme.new(theme_params)
        if theme.save
          redirect_to url_for(action: :edit, id: theme), notice: 'Theme created'
        else
          render inline: theme.errors.full_messages.join(', ')
        end
      end

      def edit; end

      def update
        if @theme.update(theme_params)
          render inline: ''
        else
          render inline: @theme.errors.full_messages.join(', ')
        end
      end

      def destroy
        @theme.destroy!
        redirect_to url_for(action: :index), notice: 'Theme destroyed'
      end

      private

      def theme_params
        fix_fields_values_param(:gaco_cms_theme)
        params.require(:gaco_cms_theme)
              .permit(:key, :title, :active,
                      field_values_attributes: permitted_field_values_params)
      end

      def set_theme
        @theme = Theme.find(params[:id])
      end
    end
  end
end

app/views/layouts/gaco_cms/_breadcrumb.html.haml
%ol.breadcrumb.mb-0.small
  - @breadcrumbs.each do |item|
    :ruby
      label, url = item
      label = t("breadcrumbs.#{label}") if label.is_a?(Symbol)
    - if @breadcrumbs.last.last == item
      %li.breadcrumb-item.active= label
    - else
      %li.breadcrumb-item= link_to(label, url, class: 'link-light')

app/views/layouts/gaco_cms/_flash_messages.html.haml
- flash.each do |msg_type, message|
  :ruby
    if %i[alert error].include?(msg_type.to_sym)
      flash_class = 'bg-danger'
    elsif %i[warning warn].include?(msg_type.to_sym)
      flash_class = 'bg-danger'
    else
      flash_class = 'bg-success'
    end
  .toast.align-items-center.text-white.border-0.fade.show{"data-bs-autohide" => "true", class: flash_class}
    .d-flex
      .toast-body= message
      %button.btn-close.btn-close-white.me-2.m-auto{"aria-label" => "Close", "data-bs-dismiss" => "toast", type: "button"}

app/views/layouts/gaco_cms/_navigation.html.haml
-########### Second NavBar
#header
  %nav.navbar.navbar-expand-lg.shadow.text-white.bg-primary.navbar-dark
    .container
      %a.navbar-brand.logo.p-0.d-flex{href: gaco_cms_admin_path, style: 'font-size: 32px;'}
        %span.text-white= GacoCms::Config.admin_title
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#main_nav_bar", "data-bs-toggle" => "collapse", :type => "button"}
        %span.fa.fa-bars

      #main_nav_bar.collapse.navbar-collapse.justify-content-end.text-white-50
        %ul.navbar-nav
          - if @custom_menus
            - @custom_menus.each do |menu|
              %li.nav-item
                %a.nav-link{href: menu[:url]}= menu[:label]
          - else
            - GacoCms::PageType.all.where(key: ['pages', 'posts']).title_ordered.each do |ptype|
              %li.nav-item
                %a.nav-link{href: gaco_cms_admin_page_type_pages_path(page_type_id: ptype)}= ptype.title
            %li.nav-item
              .vr.bg-black{ style: 'height: 100%' }
            %li.nav-item
              %a.nav-link{href: gaco_cms_admin_page_types_path}= GacoCms::PageType.human_name(count: 2)
            %li.nav-item
              %a.nav-link{href: gaco_cms_admin_themes_path}= GacoCms::Theme.human_name(count: 2)

app/views/layouts/gaco_cms/admin.haml
!!!
%html
  %head
    %title= GacoCms::Config.admin_title
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'gaco_cms'
    = javascript_include_tag 'gaco_cms'
    = javascript_tag "window.locale = '#{I18n.locale}'; window.gaco_cms_config = { \"locale\": '#{I18n.locale}', \"locales\": #{GacoCms::Config.locales.to_json}, \"editor_css\": '#{path_to_stylesheet(GacoCms::Config.backend_editor_css)}', upload_path: '#{gaco_cms_admin_upload_file_path(format: :json)}' };";

  %body#body
    = render '/layouts/gaco_cms/navigation'

    -########## Breadcrumbs
    #breadcrumb_panel.d-flex.justify-content-end.container.pt-1
      %nav{style: '--bs-breadcrumb-divider: "»";'}= render '/layouts/gaco_cms/breadcrumb'

    #main-progress-bar.progress.fixed-top.invisible{ style: 'z-index: 99999' }
      .progress-bar.progress-bar-striped.progress-bar-animated{role: "progressbar", style: "width: 100%"}
    #toasts.toast-container.position-fixed.p-3.bottom-0.end-0{ style: 'z-index: 99999' }
      = render '/layouts/gaco_cms/flash_messages'

    #container.container.pt-3
      = yield
    = turbo_frame_tag :turbo_frame_none

app/views/layouts/gaco_cms/front.html.haml
!!!
%html
  %head
    %title= GacoCms::Config.admin_title
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'gaco_cms_front'
    = javascript_include_tag 'gaco_cms_front'

  %body#body
    %nav.navbar.navbar-expand-lg.shadow.text-white
      .container
        %a.navbar-brand.logo.p-0.d-flex{href: gaco_cms_path, style: 'font-size: 32px;'}
          %span.text-black Gaco
          %span.text-primary CMS
        %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#main_nav_bar", "data-bs-toggle" => "collapse", :type => "button"}
          %span.fa.fa-bars

        #main_nav_bar.collapse.navbar-collapse.justify-content-end.text-white-50
          %ul.navbar-nav
            - GacoCms::Page.joins(:page_type).merge(GacoCms::PageType.where(key: :pages)).each do |page|
              %li.nav-item
                %a.nav-link{href: page_url_for(page.key)}= page.title
            %li.nav-item
              .dropdown
                %a.btn.dropdown-toggle{"data-bs-toggle" => "dropdown", role: "button"}= I18n.locale.to_s.upcase
                %ul.dropdown-menu
                  - GacoCms::Config.locales.each do |locale|
                    %li= link_to locale.upcase, url_for(locale: locale, params: request.query_parameters.except(:locale)), class: 'dropdown-item'

    #container.container.pt-3
      = yield