config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :gaco_cms, path: GacoCms::Config.url_path do
    namespace :admin do
      get '/', to: 'base#index'
      post 'upload_file', controller: 'base'
      resources :page_types do
        resources :pages
      end
      resources :field_groups_manager, only: %i[index update] do
        get :group_tpl, on: :collection
        get :field_tpl, on: :collection
      end
      resources :field_groups_renderer, only: :index do
        get :render_group, on: :collection
        get :render_field, on: :collection
      end
      resources :themes
    end

    # frontend
    get '/', to: 'front#index'
    get 'page/:page_id', as: 'page', to: 'front#page'
    get ':page_title-:page_id', as: 'titled_page', to: 'front#page'
    get ':type_title/:page_title-:page_id', as: 'type_titled_page', to: 'front#page'
  end
end

app/controllers/gaco_cms/admin/field_groups_renderer_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class FieldGroupsRendererController < BaseController
      before_action :set_record, only: %i[index]

      def index
        @groups = @record.field_groups
        @groups = @record.page_type.field_groups if params[:parent] && @record.is_a?(Page)
      end

      def render_group
        group = FieldGroup.find(params[:group_id])
        locals = { group: group, field_values: FieldValue.none, group_no: Time.current.to_i }
        render partial: 'group', locals: locals
      end

      def render_field
        field = Field.find(params[:field_id])
        value = field.field_values.new(group_no: params[:group_no])
        render partial: 'field', locals: { value: value }
      end

      private

      # TODO: whitelist record_types
      def set_record
        @record = params[:record_type].constantize.find(params[:record_id])
      end
    end
  end
end

app/views/gaco_cms/admin/field_groups_renderer/_field.html.haml
-# locals: { value: Value }
:ruby
  key = "#{value.id}_#{value.field_id}_#{value.field.field_group_id}_#{Time.current.to_i}"
  name = "field_values_attributes[#{key}]"

- field_tpl = capture do
  = fields_for name, value do |f|
    = f.hidden_field :id
    = f.hidden_field :field_id
    = f.hidden_field :group_no, class: 'field-group-no'
    = f.text_field :position, class: 'd-none position-field'
    = f.check_box :_destroy, class: 'd-none _destroy_field'
    .d-flex.align-items-center
      = required_label f, :title, label: value.field.title, optional: !value.required, class: 'me-2'
      %small
        %code.small= "[#{value.field.key}]"
    - if value.field.description
      .small.text-light.fst-italic= value.field.description
  = render value.field.tpl, value: value, name: name

- if value.repeat
  %li.list-group-item.ps-1.pe-1
    .row.align-items-center.gx-2
      .col.field-col= field_tpl
      .col.actions-col.col-auto.text-end{ style: 'max-width: 38px;' }
        = fields_for name, value do |f|
          = f.check_box :_destroy, 'data-controller': 'gaco-cms-deletable_row', 'data-hide-closest': '.list-group-item', 'data-hideonly': value.id, class: '_destroy_field'
        = button_tag class: 'btn btn-sm sort-btn btn-light', type: :button do
          %i.fa.fa-arrows-alt
- else
  = field_tpl

app/views/gaco_cms/admin/field_groups_renderer/_fields_frame.html.haml
-# locals: { record: Page|Theme }

.fieldset_style
  .d-flex.justify-content-end.legend_style
    = link_to gaco_cms_admin_field_groups_manager_index_path(record_type: @page.class.name, record_id: @page.id, reload_frame: '#field-groups-renderer'), class: 'btn btn-sm btn-info', 'data-title': 'Configure Fields', 'data-controller': 'gaco-cms-modal', 'data-gaco-cms-modal-size-value': 'modal-xl' do
      %i.fa.fa-gears
      Configure Fields

  %turbo-frame{ id: 'field-groups-renderer', src: gaco_cms_admin_field_groups_renderer_index_path(record_type: @page.class.name, record_id: @page.id) }
    .card{ style: 'min-height: 250px' }
      .card-body
        %h5.card-title.placeholder-glow
          %span.placeholder.col-12{ style: 'height: 50px' }
        %p.card-text.placeholder-glow
          %span.placeholder.col-12
          %span.placeholder.col-12

app/views/gaco_cms/admin/field_groups_renderer/_group.html.haml
-# locals: { group: FieldGroup, field_values: [FieldValue], group_no: Integer }
- accordion_key = "gaco_cms-field-group#{group.id}-#{group_no}"
.accordion-item
  - if group.repeat
    .accordion-header
      .accordion-button{'data-bs-target' => "##{accordion_key}", "data-bs-toggle" => "collapse"}
        = button_tag class: 'btn btn-sm group-sort-btn btn-light', type: :button do
          %i.fa.fa-arrows-alt
        = check_box_tag :_destroy, '1', false , 'data-controller': 'gaco-cms-deletable_row', 'data-propagate': '._destroy_field', 'data-hide-closest': '.accordion-item', 'data-hideonly': field_values.for_group(group).where(group_no: group_no).any?
        = "Group: #{group_no}"

  .accordion-collapse.collapse{ id: accordion_key, class: group.repeat ? '' : 'show', 'data-bs-parent': "#gaco_cms-field-group-#{group.id}" }
    .accordion-body
      %ul.list-group.list-group-flush
        - group.fields.ordered.each.with_index do |field, _i|
          %li.list-group-item{ class: "#{field.repeat ? 'list-group-item-light ps-1 pe-1 border' : 'ps-0 pe-0' }", 'data-kind': field.kind }
            - if field.repeat
              .fields-list{ 'data-controller': 'gaco-cms-repeatable-field' }
                .d-flex.justify-content-end.mb-2
                  = link_to url_for(action: :render_field, field_id: field, group_no: group_no), class: 'btn btn-sm btn-outline-primary', 'data-gaco-cms-repeatable-field-target' => 'button' do
                    = field.title
                    %i.fa.fa-plus-square
                %ul.list-group.list-group-flush{ 'data-gaco-cms-repeatable-field-target': 'list', data: { controller: 'gaco-cms-sortable', 'gaco-cms-sortable-handle-value': '.list-group-item .sort-btn', 'gaco-cms-sortable-input-selector-value': '.position-field' } }
                  - field_values.all_or_new_for(field, group_no).each do |value|
                    = render 'field', value: value, index: 0
            - else
              = render 'field', value: field_values.all_or_new_for(field, group_no).first, index: 0

app/views/gaco_cms/admin/field_groups_renderer/index.html.haml
- @groups.ordered.each do |group|
  .card.fields-list.mb-4{ 'data-controller': 'gaco-cms-repeatable-field' }
    .card-header
      .d-flex.justify-content-between
        .title
          %h4= group.title
          - if group.description.present?
            .small.italic.text-light= group.description
        - if group.repeat
          .btns
            %small
              %code.small= "[page_field_group_tpl key=#{group.key}]"
            = link_to url_for(action: :render_group, group_id: group), class: 'btn btn-sm btn-outline-primary', 'data-gaco-cms-repeatable-field-target' => 'button' do
              %i.fa.fa-plus-square
    .accordion.accordion-flush{ id: "gaco_cms-field-group-#{group.id}", 'data-gaco-cms-repeatable-field-target': 'list', 'data-controller': 'gaco-cms-sortable', 'data-gaco-cms-sortable-handle-value': '.group-sort-btn', 'data-gaco-cms-sortable-input-selector-value': 'input.field-group-no' }
      - (@record.field_values.group_nos_for(group).presence || [999]).each do |group_no|
        = render 'group', group: group, field_values: @record.field_values.eager_load(:field), group_no: group_no