config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :gaco_cms, path: GacoCms::Config.url_path do
    namespace :admin do
      get '/', to: 'base#index'
      post 'upload_file', controller: 'base'
      resources :page_types do
        resources :pages
      end
      resources :field_groups_manager, only: %i[index update] do
        get :group_tpl, on: :collection
        get :field_tpl, on: :collection
      end
      resources :field_groups_renderer, only: :index do
        get :render_group, on: :collection
        get :render_field, on: :collection
      end
      resources :themes
    end

    # frontend
    get '/', to: 'front#index'
    get 'page/:page_id', as: 'page', to: 'front#page'
    get ':page_title-:page_id', as: 'titled_page', to: 'front#page'
    get ':type_title/:page_title-:page_id', as: 'type_titled_page', to: 'front#page'
  end
end

app/models/gaco_cms/field.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: simple_cms_fields
#
#  id             :integer          not null, primary key
#  data           :text
#  def_value      :text
#  description    :text
#  key            :string
#  kind           :string           default("text_field")
#  position       :integer          default(0)
#  repeat         :boolean          default(FALSE)
#  required       :boolean          default(FALSE)
#  title          :text
#  translatable   :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  field_group_id :integer          not null
#
# Indexes
#
#  index_simple_cms_fields_on_field_group_id  (field_group_id)
#
# Foreign Keys
#
#  field_group_id  (field_group_id => simple_cms_field_groups.id)
#

module GacoCms
  class Field < ApplicationRecord
    include BuddyTranslatable
    translatable :title, :description, :def_value

    EXTRA_KINDS = GacoCms::Config.extra_fields
    KINDS = %i[text_field text_area editor file page].concat(EXTRA_KINDS.keys)
    enum kind: KINDS.map { |k| [k, k.to_s] }.to_h

    belongs_to :field_group, optional: false
    # has_one :record, through: :field_group, touch: true (TODO: failed with object 'Record#record' without 'source_type')
    has_many :field_values, dependent: :destroy, inverse_of: :field
    after_update_commit :update_values_key, if: :saved_change_to_key?

    validates :key, uniqueness: { scope: :field_group_id }
    scope :ordered, -> { order(position: :asc) }

    def self.dropdown_data
      KINDS.map do |key|
        title = key.to_s.titleize
        title = ApplicationHelper.translated_value_for(EXTRA_KINDS[key][:label]) if EXTRA_KINDS[key]
        [title, key]
      end
    end

    def default_value_tpl
      return "/gaco_cms/admin/field_groups_renderer/default_value/#{kind}" if kind == 'page'

      EXTRA_KINDS.dig(kind&.to_sym, :default_value_tpl)
    end

    def allow_translation?
      return false if %w[page].include?(kind)

      res = EXTRA_KINDS.dig(kind&.to_sym, :translatable)
      res.nil? ? true : res
    end

    def tpl
      EXTRA_KINDS.dig(kind&.to_sym, :tpl) || "/gaco_cms/admin/field_groups_renderer/fields/#{kind}"
    end

    private

    def update_values_key
      field_values.each { |v| v.update!(field_key: key) }
    end
  end
end

app/controllers/gaco_cms/admin/fields_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class FieldsController < BaseController
      before_action :set_field

      def tpl
        value = @field.field_values.new(group_no: params[:group_no])
        render partial: '/gaco_cms/admin/fields/render/field', locals: { value: value }
      end

      private

      def set_field
        @field = Field.find(params[:id])
      end
    end
  end
end

app/views/gaco_cms/admin/fields/render/_field.html.haml
-# locals: { value: Value }
:ruby
  key = "#{value.id}_#{value.field_id}_#{value.field.field_group_id}_#{Time.current.to_i}"
  name = "field_values_attributes[#{key}]"

- field_tpl = capture do
  = fields_for name, value do |f|
    = f.hidden_field :id
    = f.hidden_field :field_id
    = f.hidden_field :group_no
    = f.text_field :position, class: 'd-none position-field'
    = f.check_box :_destroy, class: 'd-none _destroy_field'
    .d-flex.align-items-center
      = required_label f, :title, label: value.field.title, optional: !value.required, class: 'me-2'
      %small
        %code.small= "[#{value.field.key}]"
    - if value.field.description
      .small.text-light.fst-italic= value.field.description
  = render value.field.tpl, value: value, name: name

- if value.repeat
  %li.list-group-item.border
    .row.align-items-center
      .col.field-col= field_tpl
      .col.actions-col.col-auto.text-end
        = fields_for name, value do |f|
          = f.check_box :_destroy, 'data-controller': 'gaco-cms-deletable_row', 'data-hide-closest': '.list-group-item', 'data-hideonly': value.id, class: '_destroy_field'
        = button_tag class: 'btn btn-sm sort-btn btn-light', type: :button do
          %i.fa.fa-arrows-alt
- else
  = field_tpl

app/views/gaco_cms/admin/fields/render/_group.html.haml
-# locals: { group: FieldGroup, field_values: [FieldValue], group_no: Integer }
- accordion_key = "gaco_cms-field-group#{group.id}-#{group_no}"
.accordion-item
  - if group.repeat
    .accordion-header
      .accordion-button{'data-bs-target' => "##{accordion_key}", "data-bs-toggle" => "collapse"}
        = check_box_tag :_destroy, '1', false , 'data-controller': 'gaco-cms-deletable_row', 'data-propagate': '._destroy_field', 'data-hide-closest': '.accordion-item', 'data-hideonly': field_values.for_group(group).where(group_no: group_no).any?

  .accordion-collapse.collapse.show{ id: accordion_key }
    .accordion-body
      %ul.list-group.list-group-flush
        - group.fields.ordered.each.with_index do |field, _i|
          %li.list-group-item{ class: "#{field.repeat ? 'list-group-item-light' : 'ps-0 pe-0' }", 'data-kind': field.kind }
            - if field.repeat
              .fields-list{ 'data-controller': 'gaco-cms-repeatable-field' }
                .d-flex.justify-content-end
                  = link_to tpl_gaco_cms_admin_field_path(id: field, group_no: group_no), class: 'btn btn-sm btn-outline-primary', 'data-gaco-cms-repeatable-field-target' => 'button' do
                    = field.title
                    %i.fa.fa-plus-square
                %ul.list-group.list-group-flush{ 'data-gaco-cms-repeatable-field-target': 'list', data: { controller: 'gaco-cms-sortable', 'gaco-cms-sortable-handle-value': '.list-group-item .sort-btn', 'gaco-cms-sortable-input-selector-value': '.position-field' } }
                  - field_values.all_or_new_for(field, group_no).each do |value|
                    = render '/gaco_cms/admin/fields/render/field', value: value, index: 0
            - else
              = render '/gaco_cms/admin/fields/render/field', value: field_values.all_or_new_for(field, group_no).first, index: 0