config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :gaco_cms, path: GacoCms::Config.url_path do
    namespace :admin do
      get '/', to: 'base#index'
      post 'upload_file', controller: 'base'
      resources :page_types do
        resources :pages
      end
      resources :field_groups_manager, only: %i[index update] do
        get :group_tpl, on: :collection
        get :field_tpl, on: :collection
      end
      resources :field_groups_renderer, only: :index do
        get :render_group, on: :collection
        get :render_field, on: :collection
      end
      resources :themes
    end

    # frontend
    get '/', to: 'front#index'
    get 'page/:page_id', as: 'page', to: 'front#page'
    get ':page_title-:page_id', as: 'titled_page', to: 'front#page'
    get ':type_title/:page_title-:page_id', as: 'type_titled_page', to: 'front#page'
  end
end

app/controllers/gaco_cms/admin/page_types_controller.rb
# frozen_string_literal: true

module GacoCms
  module Admin
    class PageTypesController < BaseController
      before_action :set_page_type, only: %i[edit update destroy]
      before_action { add_breadcrumb(PageType.human_name(count: 2), url_for(action: :index)) }

      def index
        @page_types = PageType.all.title_ordered
      end

      def new
        @page_type = PageType.new
        render :form
      end

      def create
        page_type = PageType.new(page_type_params)
        if page_type.save
          redirect_to url_for(action: :index), notice: 'PageType saved'
        else
          render inline: page_type.errors.full_message.join(', ')
        end
      end

      def edit
        render :form
      end

      def update
        if @page_type.update(page_type_params)
          redirect_to url_for(action: :index), notice: 'PageType saved'
        else
          render inline: @page_type.errors.full_message.join(', ')
        end
      end

      def destroy
        @page_type.destroy!
        redirect_to url_for(action: :index), notice: 'PageType destroyed'
      end

      private

      def page_type_params
        params.require(:gaco_cms_page_type)
              .permit(:key, :template, title: permitted_locales)
      end

      def set_page_type
        @page_type = PageType.find(params[:id])
      end
    end
  end
end

app/views/gaco_cms/admin/page_types/form.html.haml
%h2= form_title(@page_type)
.row
  = form_for(@page_type, url: url_for(action: @page_type.new_record? ? :create : :update), html: { enctype: 'multipart/form-data', class: 'col-4 col-xs-12' }) do |f|
    .field.mb-2
      = f.label :title
      = f.text_field :title, value: @page_type.title_data.to_json, class: 'form-control', required: true, data: { controller: 'gaco-cms-translatable' }
    .field.mb-2
      = f.label :key
      = f.text_field :key, class: 'form-control', required: true
    .field.mb-2
      = f.label :template
      .fw{ data: { controller: 'gaco-cms-toggle-field', 'gaco-cms-toggle-field-open-value': @page_type.template.present? } }
        = f.text_area :template, class: 'form-control', data: { controller: 'gaco-cms-editor', height: 500 }

    .field.mb-2.text-end
      = link_to url_for(action: :index), class: 'btn btn-secondary me-3' do
        Cancel

      = button_tag class: 'btn btn-primary' do
        Save
        %i.fa.fa-save

  .col-8
    .fieldset_style.mt-0
      .d-flex.justify-content-end.legend_style
        %span.bg-white Custom Fields
      %turbo-frame{ id: 'field-groups-renderer-parent', src: gaco_cms_admin_field_groups_manager_index_path(record_type: @page_type.class.name, record_id: @page_type.id, reload_frame: '#field-groups-renderer-parent') }

app/views/gaco_cms/admin/page_types/index.html.haml
%h1= GacoCms::PageType.human_name(count: 2)

.text-end
  = link_to(url_for(action: :new), class: 'btn btn-small btn-primary') do
    = GacoCms::PageType.human_name
    %i.fa.fa-plus

%table.table.table-hover
  %thead
    %tr
      %th= GacoCms::PageType.attr_label(:key)
      %th= GacoCms::PageType.attr_label(:title)
      %th= GacoCms::PageType.attr_label(:pages)
      %th

  %tbody
    - @page_types.each do |page_type|
      %tr
        %td= page_type.key
        %td= page_type.title
        %td= page_type.pages.count
        %td.text-end{ style: 'white-space: nowrap;' }
          = link_to gaco_cms_admin_page_type_pages_path(page_type_id: page_type), class: 'btn btn-secondary btn-sm me-1' do
            = GacoCms::Page.human_name(count: 2)
            %i.fa.fa-list
          = link_to '<i class="fa fa-pencil"></i>'.html_safe, url_for(action: :edit, id: page_type), class: 'btn btn-secondary btn-sm'
          = button_to '<i class="fa fa-trash"></i>'.html_safe, url_for(action: :destroy, id: page_type), class: 'btn btn-danger btn-sm', form_class: 'd-inline', method: :delete, data: { controller: 'form-confirm', confirm: 'Are you sure?' }